/**
* This file was auto-generated by the Titanium Module SDK helper for Android
* Appcelerator Titanium Mobile
* Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
* Licensed under the terms of the Apache Public License
* Please see the LICENSE included with this distribution for details.
*
*/
package tv.harukaze.ti.imobile.android;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.kroll.KrollDict;

import android.content.Context;
import android.util.DisplayMetrics;
import android.view.WindowManager;
import jp.co.imobile.android.AdView;

public class ImobileView extends TiUIView
{
	private jp.co.imobile.android.AdView imobileView =null;

	// Constructor
	public ImobileView(final TiViewProxy proxy) {
		super(proxy);
		Log.d("TAG", "create adview mid: " + TiImobile4androidModule.MId);
	    Log.d("TAG", "create adview asid: " + TiImobile4androidModule.AsId);
		imobileView = jp.co.imobile.android.AdView.create(proxy.getActivity(), TiImobile4androidModule.MId, TiImobile4androidModule.AsId);
//		imobileView = jp.co.imobile.android.AdView.create(proxy.getActivity(), 9511, 34657);
	    Log.d("TAG", "create adview mid: " + TiImobile4androidModule.MId);
	    Log.d("TAG", "create adview asid: " + TiImobile4androidModule.AsId);
		//解像度によらないサイズ指定(高さ50dp)
//		DisplayMetrics metrics = new DisplayMetrics();
//		((WindowManager) this.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay().getMetrics(metrics);
//		int height = (int)(50 * metrics.density);
	    
	    setNativeView(imobileView);
	}

	@Override
	public void processProperties(KrollDict d){
		super.processProperties(d);
	}
}