/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package tv.harukaze.ti.imobile.android;

import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.proxy.TiViewProxy;

import android.app.Activity;
import tv.harukaze.ti.imobile.android.ImobileView;

// This proxy can be created by calling Timedibaad4android.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=TiImobile4androidModule.class)
public class ImobileViewProxy extends TiViewProxy
{
	// Standard Debugging variables
	private ImobileView adView;
	
	// Constructor
	public ImobileViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity arg0) {
		adView = new ImobileView(this);
		return adView;
	}
}